/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.app.Records;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class uRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3654915759570418671L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"uRecord\",\"namespace\":\"com.app.Records\",\"fields\":[{\"name\":\"n\",\"type\":\"long\"},{\"name\":\"type\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<uRecord> ENCODER =
      new BinaryMessageEncoder<uRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<uRecord> DECODER =
      new BinaryMessageDecoder<uRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<uRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<uRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<uRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<uRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this uRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a uRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a uRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static uRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long n;
   private java.lang.CharSequence type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public uRecord() {}

  /**
   * All-args constructor.
   * @param n The new value for n
   * @param type The new value for type
   */
  public uRecord(java.lang.Long n, java.lang.CharSequence type) {
    this.n = n;
    this.type = type;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return n;
    case 1: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: n = (java.lang.Long)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'n' field.
   * @return The value of the 'n' field.
   */
  public long getN() {
    return n;
  }


  /**
   * Sets the value of the 'n' field.
   * @param value the value to set.
   */
  public void setN(long value) {
    this.n = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Creates a new uRecord RecordBuilder.
   * @return A new uRecord RecordBuilder
   */
  public static com.app.Records.uRecord.Builder newBuilder() {
    return new com.app.Records.uRecord.Builder();
  }

  /**
   * Creates a new uRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new uRecord RecordBuilder
   */
  public static com.app.Records.uRecord.Builder newBuilder(com.app.Records.uRecord.Builder other) {
    if (other == null) {
      return new com.app.Records.uRecord.Builder();
    } else {
      return new com.app.Records.uRecord.Builder(other);
    }
  }

  /**
   * Creates a new uRecord RecordBuilder by copying an existing uRecord instance.
   * @param other The existing instance to copy.
   * @return A new uRecord RecordBuilder
   */
  public static com.app.Records.uRecord.Builder newBuilder(com.app.Records.uRecord other) {
    if (other == null) {
      return new com.app.Records.uRecord.Builder();
    } else {
      return new com.app.Records.uRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for uRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<uRecord>
    implements org.apache.avro.data.RecordBuilder<uRecord> {

    private long n;
    private java.lang.CharSequence type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.app.Records.uRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.n)) {
        this.n = data().deepCopy(fields()[0].schema(), other.n);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing uRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.app.Records.uRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.n)) {
        this.n = data().deepCopy(fields()[0].schema(), other.n);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'n' field.
      * @return The value.
      */
    public long getN() {
      return n;
    }


    /**
      * Sets the value of the 'n' field.
      * @param value The value of 'n'.
      * @return This builder.
      */
    public com.app.Records.uRecord.Builder setN(long value) {
      validate(fields()[0], value);
      this.n = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'n' field has been set.
      * @return True if the 'n' field has been set, false otherwise.
      */
    public boolean hasN() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'n' field.
      * @return This builder.
      */
    public com.app.Records.uRecord.Builder clearN() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.app.Records.uRecord.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.app.Records.uRecord.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public uRecord build() {
      try {
        uRecord record = new uRecord();
        record.n = fieldSetFlags()[0] ? this.n : (java.lang.Long) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<uRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<uRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<uRecord>
    READER$ = (org.apache.avro.io.DatumReader<uRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.n);

    if (this.type == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.type);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.n = in.readLong();

      if (in.readIndex() != 0) {
        in.readNull();
        this.type = null;
      } else {
        this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.n = in.readLong();
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.type = null;
          } else {
            this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










